### ISSUE TITLE
Website Updates & Other Important Information... 

### ISSUE THREAD

**Issue by Ibuprophen** [pbatard/rufus-web#1]
@pbatard, I wasn't sure if this is was where to provide the Website specific updates but, here they are... :-) 

The following are just to provide further elaboration/suggestions regarding the updates for your website as discussed within the https://github.com/pbatard/rufus/issues/1224 issue. 

The Official Windows 10 ISO Downloader:
https://www.microsoft.com/en-us/software-download/windows10ISO

The Official Microsoft Windows and Office ISO Download Tool:
https://www.heidoc.net/joomla/technology-science/microsoft/67-microsoft-windows-and-office-iso-download-tool

The following link is to various Microsoft Software Downloads for Office, Windows, etc... Under Various Operating System Environments and Languages. 
https://www.heidoc.net/joomla/technology-science/microsoft

I was going to provide a few Pull Requests but, I had realized that I may not be placing the information where you may prefer to have them. 

I hope that this is helpful in some way for a better experience and tools for everyone. 

Please let me know if you require any further information and I'll do what I can to help you out. 

Thank you very much for your time, patience, support and understanding! :-) 

~Ibuprophen

**Comment by pbatard** [comment]
@ibuprophen1, thanks for the suggestions. However, as I explained in the other issue, I am not planning to change links even if they may not result in most people being able to download a retail ISO from them. If you have an MSDN subscription (only legal way to download older Windows ISOs) or use a browser that does not identify itself as one running on a modern Windows platform, then all the links provided are very much valid to download retail ISOs straight from Microsoft. So I would rather avoid referencing non official ways of downloading these ISOs (even if the content from the non-official tools does come directly from Microsoft's servers, which I am well aware of).

Still, I appreciate your suggestions.

I will close this issue now.

**Comment by Ibuprophen** [comment]
Not necessarily @pbatard... 

The following are just 2 examples of guidance provided by Microsoft representatives reflecting that the downloads provided by HeiDoc are legal. 

https://answers.microsoft.com/en-us/windows/forum/all/downloading-windows-isos-legally/9b5b2ca7-8c0a-4ec1-9932-ae2555e41749

https://answers.microsoft.com/en-us/windows/forum/all/using-media-creation-tool-i-cannot-download/bd0d8ef1-c222-4751-ac4c-d96e1028efbe

As a former certified Microsoft OEM System Builder as well as having multiple other certifications with Microsoft I do try to keep up to date with various areas of the certifications. 

Microsoft's stance is that only 2 outside websites can legally provide their Software ISO which are "Digital River" and "HeiDoc". 

I'm just surprised that this isn't as well known as it should be... 


~Ibuprophen

**Comment by pbatard** [comment]
But heidoc.net is __not__ an official Microsoft site and there is no guarantee that the owner is not going to try to monetize the download tool or do other things tomorrow.

If Microsoft really saw the download tool provided on heidoc as an official one, then they would provide that tool from a Microsoft address. The fact that they don't will always make me question any "official" information provided on what is essentially a user forum. 

Besides, as I indicated, the user-agent is a well known trick to get to the retail ISOs straight from a microsoft.com URL, so I really see no reason to change it, sorry.

**Comment by Ibuprophen** [comment]
HeiDoc is one of two servers contracted by Microsoft in order to save money from running a high level of Disks.

Microsoft also allows you to look up SHA1 hashes, file names, file sizes, release dates, and other metadata of original Microsoft product downloads on the MSDN Subscriber Downloads area for all the HeiDoc downloads obtained by users as a way to verify whether a given file is genuine, or has been tampered with. 

Microsoft prefers to identify the Key Code (Activation Code) to identify the authenticity of the purchase rather than the Disks/Images. 

Here's one of their Q&A statements:
"Q: How can I install Windows from a USB drive?
A: We recommend using Rufus for that. "




~Ibuprophen

**Comment by pbatard** [comment]
> HeiDoc is one of two servers contracted by Microsoft in order to save money from running a high level of Disks.

Do you have official confirmation of this, besides posts in a user forum that is apparently impossible to access anonymously? If Microsoft wants this information to be known, then they sure as hell aren't doing a great job at making sure it is seen and/or spread around

> Microsoft also allows you to look up SHA1 hashes, file names, file sizes, release dates, and other metadata of original Microsoft product downloads on the MSDN Subscriber Downloads area for all the HeiDoc downloads obtained by users as a way to verify whether a given file is genuine, or has been tampered with.

Well, the thing is, if you have an MSDN subscription, then you will get the download links straight of the msdn microsoft URL. In other words (at least last time I checked), the MSDN didn't stop short of providing you with a download link or told you to go to a different site (HeiDoc) to access the downloads.

Furthermore, unless you apply some more browser trickery, as a non MSDN susbcriber, you can no longer get the SHA-1 and all the good stuff that was __super useful__ to validate that whatever download you got outside of the Microsoft servers was genuine. Which means that directing people to HeiDoc as non MSDN subscribers is pretty much moot, since (officially) they can't validate the SHA-1 without a valid MSDN subscription, and if they do have a valid MSDN subscription, then they can get the download link of MSDN anwyay...

> Here's one of their Q&A statements:
> "Q: How can I install Windows from a USB drive?
> A: We recommend using Rufus for that. "

Well, to me that is actually __clear proof__ that whoever made that statement doesn't speak for Microsoft, and therefore that the other statements you point to also have to be taken with a grain of salt.

Yes, I do know __some__ Microsoft people actually prefer using Rufus vs their own media creation tool (I've had a few reports from Microsoft employees telling me so). But that doesn't mean that the official stance from Microsoft has changed with regards to their media creation utility being the __only__ utility they can and will officially recommend. As long as they don't put a big link to Rufus on any of the webpage (in the microsoft.com domain) where they advise people on how to officially install Windows, then, __NO__, they are not recommending Rufus at all, and any statement that says otherwise should be considered as the __opinion__ of the person who posted it (which may also happen to be a Microsoft employee), and not a reflection of any official stance from Microsoft as a whole. As far as I know, the Microsoft DVD  USB Creation tool is still their recommended way of installing Windows from a retail/MSDN ISO, especially as they went to a lot of trouble to sort out some license compliance issue they had for that software. Considering that, as far as I am concerned, I have only seen them taking kind of a hostile stance against the use of Rufus, by preventing people to easily download Windows 10 ISOs for instance, I seriously doubt they are going to officially advocate the use of Rufus for installation anytime soon. Or, at the very least if they do, then I would very much like them to contact me first, so that I can tell them about some of the massive pain points users have with Windows installation, so that we can work towards a conciliated resolution of these issues. Plus I'm sure there is stuff that they'd like to see Rufus support, that I haven't added so far, and that they could probably help with if they value their users. At least, as far as I'm concerned, I do expect that if a company officially recommends a product from a third party, they will contact said third party to ensure that their and the other people's goals align. But that hasn't happened at all, which makes me very doubtful about any statement indicating that Microsoft "may" recommend Rufus...

**Comment by Ibuprophen** [comment]
I've got a feeling @pbatard, that no matter what, how, where, etc... the proof is from, to, about, etc... Your going to question it in opposition. 

I'll just leave this topic alone and just thank you for your excellent development and support My Friend! :-) 


~Ibuprophen

**Comment by pbatard** [comment]
> I've got a feeling @pbatard, that no matter what, how, where, etc... the proof is from, to, about, etc... Your going to question it in opposition.

You're probably right. The problem I have is I can't see any logic behind Microsoft wanting to promote HeiDoc as a legitimate download site for everybody, while not making sure they place said links on a webpage off microsoft.com. It would be very easy for them to do so, and it would reassure users who don't want to have to dig up the history of the relationship netween HeiDoc and Microsoft.

It's a bit like Akamai. Akamai used to be (and probably still is) used to distribute large volume download content, for major corporations. But these corporations always made sure that, when they provided content that was ultimately delivered by Akamai, the link for that content was always on a website that fell under the company's name, which of course, is what users expect. I hope you can understand how, no matter how many assurances we seem to get from Microsoft employees, it'll be hard to convince regular users that HeiDoc is really being endorsed by Microsoft unless there is a public (i.e. non-subscriber) webpage with links to HeiDoc downloads at ####.microsoft.com. And as long as that doesn't happen, and I can't point to that microsoft.com web page, I am going to continue to point to the only microsoft.com ISO download links I know off, that, sadly, happen to be either for MSDN subscribers or, require browser trickery to get the microsoft.com  page actually display the relevant content. 

Then again, I believe I should have a real test of whether Microsoft, as a company, is indeed fine with people slurping their public ISOs off whatever server they want to promote, as well as whether they are fine with endorsing Rufus as a Windows installation tool, once I get to add some more features I have in mind. But since it'll probably be another year or two before I do that, that's all I'm going to say about this.

> I'll just leave this topic alone and just thank you for your excellent development and support My Friend! :-)

Okay. I appreciate your help too, even if I may decide not to use it. 😄
