### ISSUE TITLE
CDBurnerXP installer PUPs

### ISSUE THREAD

**Issue by marcosfrm** [pbatard/rufus-web#17]
So CDBurnerXP is in the same boat with ImgBurn...

https://github.com/pbatard/rufus/issues/1599

At least they offer installers without the crap:

https://cdburnerxp.se/download?more-options

(Without installCore/Portable/MSI: https://forum.cdburnerxp.se/topic/10354-clarification-of-installcore/?do=findComment&comment=39481)

Be aware!

**Comment by pbatard** [comment]
Goddammit!

Can't people not release software for free these days, without succumbing to the lies of marketers who promise them heaps of financial rewards if only they would integrate their malware crap into their product (and yeah, because Rufus is successful, I too receive a constant flurry e-mails from these assholes)...

At least there's an opt out, which I hope is explicit enough, because short of statically linking to the 4.5.8.7128 x64 installer (which I might still do), there's no global link I can use to point users to the non "installCore" version.

Oh and you gotta love how these marketers give nondescript names to their "platform", that looks vaguely related to a legitimate installation operation, to stuff that should never EVER be part of a software installer...

**Comment by pbatard** [comment]
I am now linking the CDBurnerXP downloads to https://www.fosshub.com/CDBurnerXP.html which I believe are non InstallCore version, so I will close this issue.
