### ISSUE TITLE
SSL issue when download file via Rufus.

### ISSUE THREAD

**Issue by tvcat** [pbatard/rufus-web#22]
I tried download the file with curl and received the same error message. Below is the full logs.

```
Rufus x64 v4.2.2074 (Portable)
Windows version: Windows 10 Home x64 (Build 19045.3570)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 2.0 device 'PNY Hook Attache USB Device' (154B:6002)
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1939, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {5CFF9CC9-1437-4626-BDB6-138E2D777924}
Max parts: 128, Start Offset: 17408, Usable = 15955098112 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: NTFS
  ID: {971EE50C-16B4-4450-A947-E2113EA20440}
  Size: 14.9 GB (15952978944 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  Detected File System: FAT12
  ID: {7F18C13A-DC4F-46F4-B252-A9F54F4CCE78}
  Size: 512 KB (524288 bytes)
  Start Sector: 31160210, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/boot/syslinux/syslinux.cfg' for Syslinux
  Detected Syslinux version: 6.03 (from '/boot/isolinux/isolinux.bin')
  Reported Grub version: 2.06-13
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'MX-Live'
  Size: 2.1 GB (Projected)
  Note: File on disk is larger than reported ISO size by 192 KB...
  Uses: Syslinux/Isolinux v6.03
  Uses: GRUB2 (2.06-13)
  Uses: EFI
Using image: MX-23.1_x64.iso (2.1 GB)
Downloading https://rufus.ie/files/grub-2.06-13/core.img
Unable to send request: SSL certificate date that was received from the server is bad. The certificate is expired.
Downloading https://rufus.ie/files/grub-2.06/core.img
Unable to send request: SSL certificate date that was received from the server is bad. The certificate is expired.
Downloading https://rufus.ie/files/grub-2/core.img
Unable to send request: SSL certificate date that was received from the server is bad. The certificate is expired.
https://rufus.ie/files/grub-2/core.img was not found - will use embedded version
Downloading https://rufus.ie/files/syslinux-6.03/ldlinux.sys
Unable to send request: SSL certificate date that was received from the server is bad. The certificate is expired.
Could not download the file - cancelling

Found USB 2.0 device 'PNY Hook Attache USB Device' (154B:6002)
1 device found
Disk type: Removable, Disk size: 16 GB, Sector size: 512 bytes
Cylinders: 1939, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 2
Disk GUID: {5CFF9CC9-1437-4626-BDB6-138E2D777924}
Max parts: 128, Start Offset: 17408, Usable = 15955098112 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: NTFS
  ID: {971EE50C-16B4-4450-A947-E2113EA20440}
  Size: 14.9 GB (15952978944 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2 (UEFI:NTFS):
  Type: Microsoft Basic Data Partition
  Name: 'UEFI:NTFS'
  Detected File System: FAT12
  ID: {7F18C13A-DC4F-46F4-B252-A9F54F4CCE78}
  Size: 512 KB (524288 bytes)
  Start Sector: 31160210, Attributes: 0x0000000000000000
```

**Comment by pbatard** [comment]
Do you still see the error? If you do, then the issue appears to be on your end.

I am unable to replicate it, and, for what is worth, the SSL certificates are __NOT__ generated by us but by GitHub (through Let's Encrypt), so if there was an issue like the one you described, a lot of sites hosted by GitHub would be affected besides rufus.ie and GitHub would see it and fix it almost immediately.

My guess is that you somehow have the wrong date on the computer you tested. Did you validate that your current date was correct?

**Comment by tvcat** [comment]
Yes, the date on my computer is correct. I can download the file with browser but not with Rufus and curl.

Tried curl to download from Google Drive and Github raw file (both HTTPS) and it is ok.

Which other similar hosting on the Github I can test with?

**Comment by pbatard** [comment]
I don't know what other sites you can test. I'm not a GitHub repository cataloguer.

Much better to use your browser to validate the certificate, so that it can be demonstrated that whatever you are seeing is not an issue with the certificate being expired.

Just navigate to https://rufus.ie and then click on the lock icon in the address bar and follow prompts until you can access the certificate properties and export it or see its date validity fields.

[Here](https://github.com/pbatard/rufus-web/files/12928263/rufus.ie.crt.zip) is the current certificate you get, and as you should be able to __validate for yourself__ the validity is 2023.09.20 to 2023.12.19: 

![Image1](https://github.com/pbatard/rufus-web/assets/1206968/f3f44cf5-aa58-4bc3-b97e-d5b10cc399f4)

Therefore, if your system reports an error telling you that the SSL certificate is expired, you need to figure out why your system is unable to validate that the SSL certificate for rufus.ie is actually valid.

Maybe you can try to download the SSL cert through `curl` and see what you get.

For the record, if this was a widespread issue, I would get __a lot__ of reports about this (since Rufus is downloaded about 3 million times each month), but yours is the only one. Therefore, I can only conclude that your issue is squarely with your environment, and, as such, I am unwilling to spend time helping you troubleshoot something that seems specific to your system.

**Comment by tvcat** [comment]
Ok thanks.
