### ISSUE TITLE
Enforcing https for rufus.ie?

### ISSUE THREAD

**Issue by tatamu-fold** [pbatard/rufus-web#6]
Probably a good idea as rufus is now widely used... You can refer to https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site for details.

Thanks!
Happy new year!

**Comment by pbatard** [comment]
Except some people still use Windows XP and Windows 7 where the SSL version used by GitHub is too modern, and therefore are not able to access it through HTTPS.

And before you say _"Screw those XP and 7 users, they should have upgraded their system anyway!"_, remember that Rufus is a utility that can be used to migrade to a newer version of Windows, therefore it might be important for them to be able to access the web page (though they may not be able to download it directly since the download links are using HTTPS).

Note that this is a different issue from XP and 7 users not being able to download Syslinux or GRUB files in Rufus (since we __do__ enforce only HTTPS downloads in Rufus), as, in this case, XP and 7 users are not using Rufus to migrade their systems, and therefore the need to access these files using an SSL library that is too old becomes irrelevant.

At any rate, people who want to access the site through a modern (read: not yet known to be vulnerable) version of SSL can do it, so there's little point of enforcing it. Plus all the Rufus executables are digitally signed, which makes a MITM attack on the downloads quite difficult to accomplish unless you're a government agency with next to unlimited funds. But then again, what people fail to realize, and that is worth repeating, is that HTTPS is __not__ a panacea. If you really want to get people to download compromised executables, all you have to do is either submit a subpoena (if you're gov), or find a flaw or directly threaten someone who has access to the server content to insert your malicious content, and no amount of securing connections to your server with HTTPS will ever protect people against that. That's actually the reason why we have a [second layer of security on all our downloads in Rufus](https://github.com/pbatard/rufus/wiki/Security#Overall_download_signature_verification), that goes way beyond the level of "protection" HTTPS can offer, because we do consider that, at any time, the server we download files from can have been compromised.

As I believe I have answered your query, I will close this issue.
