### ISSUE TITLE
"Vandalism": Revert ko_KR.html

### ISSUE THREAD

**Issue by kiding** [pbatard/rufus-web#8]
A seemingly benign commit https://github.com/pbatard/rufus-web/commit/35718943378199db2f34a4c602ff99dc01873de8 somehow introduced _a massive diff_ only in `ko_KR.html`. The changes were written by @rlarjsdn122, where they credited themself in the code.

https://github.com/pbatard/rufus-web/blob/35718943378199db2f34a4c602ff99dc01873de8/ko_KR.html#L456

For the full context, see https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7935. But **tl;dr** is that any translation change credited to `rlarjsdn122` must be considered **"controversial,"** and should be accepted with extra caution. 

Most of the Korean speakers will consider this totally broken:

https://github.com/pbatard/rufus-web/blob/35718943378199db2f34a4c602ff99dc01873de8/ko_KR.html#L246-L256

https://github.com/pbatard/rufus-web/blob/35718943378199db2f34a4c602ff99dc01873de8/ko_KR.html#L313-L322

**Comment by pbatard** [comment]
Okay. The reason the update appeared in the wrong commit is that I forgot to propagate all the changes from commit aa93f11c72012d3a53c5829f7a5fb5c3b76f81d6. So they got applied in the next commit. So that change wasn't exactly hidden.

Obviously, I don't speak Korean, so it's difficult for me to detect malicious updates, and vetting all localization changes before applying them would simply take too much time.

I will revert these changes as soon as I get a chance. Thanks for pointing it out!

**Comment by pbatard** [comment]
Changes should be reverted now (it may take some time for GitHub to update the site).

I'm going to close this issue with the commit that reverts the changes, but if you still see a problem, please let me know.

**Comment by kiding** [comment]
Missed that commit. Sorry about that!

Thanks for the quick response. Cheers.
